# Creating Random Arrays with Numpy

## Introduction

This notebook was created by [Jupyter AI](https://github.com/jupyterlab/jupyter-ai) with the following prompt:

> /generate Create a Jupyter notebook that shows how to create a random array using numpy.

This Jupyter notebook demonstrates how to create a random array using numpy. It covers topics such as importing necessary packages, creating a random array, setting the array size and shape, setting the data type of the array, and generating a random array with specified parameters. Each section includes sample code for creating a random array and printing the results. This notebook is useful for anyone looking to generate random arrays in their data analysis or machine learning projects.

## Creating a random array

In [1]:
import numpy as np

In [2]:
np.random.seed(123)
random_array = np.random.rand(3, 4)

In [3]:
print("Random array:\n", random_array)

Random array:
 [[0.69646919 0.28613933 0.22685145 0.55131477]
 [0.71946897 0.42310646 0.9807642  0.68482974]
 [0.4809319  0.39211752 0.34317802 0.72904971]]


## Setting the array size and shape

In [4]:
import numpy as np

In [5]:
# Set the size and shape of the random array
array_size = (3, 4) # number of rows and columns

In [6]:
# Create the random array using the specified size and shape
random_array = np.random.rand(*array_size) # *array_size unpacks the tuple

In [7]:
# Print the random array
print("Random array:\n", random_array)

Random array:
 [[0.43857224 0.0596779  0.39804426 0.73799541]
 [0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351]]


## Setting the data type of the array

In [8]:
import numpy as np

In [9]:
# Set the data type of the random array to be created
dtype = np.int32

In [10]:
# Set the size and shape of the random array
array_size = (3, 4) # number of rows and columns

In [11]:
# Create the random array using the specified size, shape, and data type
random_array = np.random.randint(low=0, high=10, size=array_size, dtype=dtype)

In [12]:
# Print the random array
print("Random array:\n", random_array)

Random array:
 [[4 6 1 5]
 [6 2 1 8]
 [3 5 0 2]]


## Generating a random array with specified parameters

In [13]:
import numpy as np

In [14]:
array_size = (5, 7) 
min_val = -10
max_val = 10

In [15]:
def create_random_array(size, low, high):
    return np.random.randint(low=low, high=high, size=size)

In [16]:
random_array = create_random_array(array_size, min_val, max_val)

In [17]:
print("Random array:\n", random_array)

Random array:
 [[ 0  3  8 -6  5  1  2]
 [-4  3  9  6 -4  4 -3]
 [ 1 -3 -9  1 -5  8  7]
 [ 2  8  7 -9  9  2 -1]
 [ 6  7 -7 -7  1 -3 -1]]
